domain:
  host: www.example.com
dropbox:
  upload_uri: smb://www.example.com/dropbox
auth:
  configuration:
    - :name: Avalon Test Auth
      :provider: :identity
      :params:
        :fields:
          - :email
    - :name: Avalon Lti OAuth
      :provider: :lti
      :hidden: true
      :params:
        :oauth_credentials:
          key: 'secret'
encoding:
  engine_adapter: test
email: 
  mailer:
